matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
    - os: linux
      services: docker
      language: generic
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e ELECTRON_CACHE=$HOME/.cache/electron \
        -e ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm install && npm run build -- --linux --win"
    else
      npm run build
    fi
  - ls -lR build
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
