cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_script:
  - echo "SENTRY_DSN=$SENTRY_DSN" >> .env
  - echo "GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID" >> .env

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode11
      language: node_js
      node_js: 10
      before_script:
        - curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64" > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: npm run test
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - &build-mac
      stage: build-mac
      os: osx
      osx_image: xcode11
      language: node_js
      node_js: 10
      if: branch = master AND type = push
      script: npm run build -- --mac

    - &build-linux-win
      stage: build-linux-win
      os: osx
      osx_image: xcode11
      language: node_js
      node_js: 10
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      if: branch = master AND type = push
      script: ./scripts/build-linux-win.sh

    - stage: build-test-mac
      <<: *build-mac
      if: type = pull_request
      script: npm run build -- --mac -p never

    - stage: build-test-linux-win
      <<: *build-linux-win
      if: type = pull_request
      script: ./scripts/build-linux-win.sh -p never
